version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: wow
      POSTGRES_PASSWORD: "7f7FD77-Gid6_JUAbC6SCrewkOHlIJPO"
    volumes:
      - wow_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "1cR3D6TRLzISZV5mqyVp1Ta-hayUgslk"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  wow_data:
